services:
  streamui-web-server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: streamui-web
    container_name: streamui-web-server
    command: "bash start.sh"
    network_mode: "host"
    environment:
      - TZ_NAME=${TZ_NAME:-UTC}
      - ZLM_CONTAINER_NAME=zlm-server
      - STREAMUI_CONTAINER_NAME=streamui-web-server
      - ZLM_HTTP_PORT=${ZLM_HTTP_PORT:-8080}
      - ZLM_RTSP_PORT=${ZLM_RTSP_PORT:-8554}
      - ZLM_RTMP_PORT=${ZLM_RTMP_PORT:-1935}
      - ZLM_RTC_PORT=${ZLM_RTC_PORT:-8000}
    volumes:
      - .:/workspace
      - ./record:/opt/media/bin/www/record
      - ./conf:/opt/media/conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    depends_on:
      - zlm-server

  zlm-server:
    image: zlmediakit/zlmediakit:master
    container_name: zlm-server
    ports:
      - "1935:1935"
      - "8080:80"
      - "8443:443"
      - "8554:554"
      - "10000:10000"
      - "10000:10000/udp"
      - "8000:8000/udp"
      - "9000:9000/udp"
    volumes:
      - ./record:/opt/media/bin/www/record
      - ./conf:/opt/media/conf
      - ./log:/opt/media/bin/log
    restart: unless-stopped